require "uifaces/version"

module UIFaces
  def self.face(index = nil)
    index ||= rand(0..UIFACES.size - 1)
    index = index % UIFACES.size
    "http://uifaces.com/faces/_twitter/#{UIFACES[index]}_120.jpg"
  end

  UIFACES = %w(
    jayrobinson
    VinThomas
    ShaunMoynihan
    jayman
    damenleeturks
    kolage
    rogie
    jacobseethaler
    calebogden
    blakesimkins
    nckjrvs
    cameronmoll
    gilbertglee
    alagoon
    kirkouimet
    zulsdesign
    danielhaim
    garrettgee
    ripplemdk
    timothycd
    daryl
    ogvidius
    motherfuton
    andrewpautler
    WhatTheFerguson
    pizzulata
    dbox
    deimler
    antoniopratas
    Djeje
    molovo
    owlfurty
    OskarLevinson
    redkeg
    russellsmith21
    benefritz
    decarola
    mkalalang
    kristijantaken
    iamlouisbullock
    vctrfrnndz
    daniel_love
    jonsuh
    leevigraham
    utroda
    JuliaYunLiu
    gabediaz
    Alvaro_Nistal
    benpeck
    Anotherdagou
    ryanleroux
    haibnu
    todd_coleman
    ThisIsJohnBrown
    axelbouaziz
    ryanAmurphy
    AngelZxxWingZ
    mikebeecham
    tiagocamargo
    jsngr
    benhowdle
    feliperibeiros
    jpadilla_
    _joshnh
    MarkusOkur
    imfine_thankyou
    matejsudar
    ckor
    ariona_rian
    roybarberuk
    eldelentes
    nimaa
    sajtoo
    bradenhamm
    PtiteNoli
    NastyaVZ
    walterstephanie
    mds
    designer_dean
    itolmach
    JeffChausse
    CrafterSama
    vehbikilic
    jcarlosweb
    renbyrd
    max9xs
    Fitehal
    iamlouisbullock
    gerwitz
    Fubaruba
    hvillega
    waqar_alamgir
    desaiguddu
    mambows
    fabioChannel
    ryanlfoster
    macvhustle
    Rafa3mil
    toodlenoodle
    jwphillips
    alek_djuric
    calvintennant
    cibawoman
    mcmieras
    jjmpsp
    rizwaniqbal
    neweravin
    temonehm
    acoops_
    smharley
    odaymashalla
    meddeg
    FreelanceNathan
    luhman
    adn
    wrightmartin
    brampitoyo
    iamjamie
    dvidsilva
    arjunchetna
  )
end
